### ISSUE TITLE
Czech Republic spelt wrong in English

### ISSUE THREAD

**Issue by dueyfinster** [marc-ed-raffalli/geo-game#2]
Appears as Czechia 🇨🇿

**Comment by marc-ed-raffalli** [comment]
The country was actually renamed to Czechia recently
- http://www.independent.co.uk/news/world/europe/czechia-czech-republic-new-name-english-speakers-a7323596.html
- https://goo.gl/maps/xTVMxtwkLUu

**Comment by dueyfinster** [comment]
Ah didn’t know that! Cool project Marc, hope your doing well.

**Comment by marc-ed-raffalli** [comment]
Thanks Neil, really hope it will help people as much as it helped me remembering the name and location.
Take care! :)
